/**
 * Bake VELORA_APP_URL into the packaged app (no secrets — public HTTPS only).
 * Usage: set VELORA_APP_URL=https://….railway.app && npm run dist:win
 */
const fs = require('fs')
const path = require('path')

const url = (process.env.VELORA_APP_URL || '').trim().replace(/\/$/, '')
const out = path.join(__dirname, '..', 'app-config.cjs')

fs.writeFileSync(
  out,
  `// Generated by scripts/write-config.cjs — do not commit secrets\n` +
    `module.exports = { VELORA_APP_URL: ${JSON.stringify(url)} }\n`,
  'utf8',
)

if (!url) {
  console.warn(
    '[velora-desktop] VELORA_APP_URL boş — kurulum sihirbazı uyarı ekranı gösterir.',
  )
} else {
  console.log('[velora-desktop] VELORA_APP_URL baked:', url)
}
